### ISSUE TITLE
悄悄问一下，这个算破解版吗 

### ISSUE THREAD

**Issue by Bluky-BlueSky** [L-M-Sherlock/sm18-lazy-package#1]
在试图申请visa卡来购买正版无果之后突然发现了这个版本，是不是意味着在我申请到visa卡之前可以无限使用supermemo18的所有功能了（甚至都被汉化了）

**Comment by L-M-Sherlock** [comment]
不算，因为用的是我的序列号，所以这是正版。

**Comment by Bluky-BlueSky** [comment]
![image](https://user-images.githubusercontent.com/78255599/142626208-17396fe6-1782-4363-ab04-8d6aae9c49a9.png)
是因为这个所以可以分享给别人自己已经购买的SuperMemo吗 
以及这个被分享的SuperMemo在功能上会受到什么限制吗 还是说会跟分享者自己的SuperMemo的可用功能完全一样

**Comment by L-M-Sherlock** [comment]
和购买者的完全一致。就和你玩以前的老游戏，要输入 CD-key 一样。CD-key 输入正确，所有功能都一样的。

**Comment by Bluky-BlueSky** [comment]
这个就跟在GOG买了游戏下载之后拷贝给朋友玩差不多对吗

**Comment by L-M-Sherlock** [comment]
是的

**Comment by Bluky-BlueSky** [comment]
了解！感谢大佬分享！OTZ
