### ISSUE TITLE
Times Ten LT Std + FZYouSongS R无法正常显示“——”、“==”字符

### ISSUE THREAD

**Issue by Zacharia2** [L-M-Sherlock/sm18-lazy-package#13]
![image](https://github.com/L-M-Sherlock/sm18-lazy-package/assets/32425955/b7a3f2ab-274a-4f13-a453-2ecfc4790172)

**Comment by L-M-Sherlock** [comment]
@Aria-stack 你有遇到这个问题吗？

**Comment by L-M-Sherlock** [comment]
合并字体有点问题，建议把css里面的字体删掉，用默认字体。

**Comment by Zacharia2** [comment]
OK
