### ISSUE TITLE
佬，想问一下我是在macbook m1芯片下通过虚拟机上的win11下载的，为什么打开软件就界面出现一秒就闪退呢？

### ISSUE THREAD

**Issue by kunls** [L-M-Sherlock/sm18-lazy-package#14]

**Comment by L-M-Sherlock** [comment]
尝试用兼容模式打开。

**Comment by kunls** [comment]
> 尝试用兼容模式打开。

您好，我使用兼容模式打开后依旧是闪屏一下就闪退，如附件所示，请问佬如何处理呢？
![supermemo闪退问题](https://github.com/L-M-Sherlock/sm18-lazy-package/assets/94953726/96dc7d0f-95f2-4f2a-aec8-f5804576caf7)

**Comment by L-M-Sherlock** [comment]
你的supermemo的路径是纯英文吗？

**Comment by kunls** [comment]
是的，是纯英文。\\Mac\Home\Downloads\sm18-lazy-package-main\sm18

**Comment by kunls** [comment]
<img width="1440" alt="image" src="https://github.com/L-M-Sherlock/sm18-lazy-package/assets/94953726/e82181ae-418e-4ca6-9db4-ca26bf0d58ab">
但是all in one似乎可以打开，只是报了几个错，请问使用这个和那个有什么区别吗？

**Comment by kunls** [comment]
通过下官网的版本手动导入汉化成功了，感谢叶佬
