### ISSUE TITLE
建议把 supermemo 的快捷键表作为 渐进阅读素材 加入进去

### ISSUE THREAD

**Issue by MilkBlock** [L-M-Sherlock/sm18-lazy-package#3]
去年使用supermemo的时候总是不知道快捷键哪里找
对于英文不好的人不大友好
所以不妨把官网上快捷键的内容放进去

对于这种快捷键文章，这种高信息密度，高筛选和记忆的需求的文章
supermemo能直观的展示自己的力量
同时又能把握supermemo的快捷键框架
我认为在懒人包里放这篇非常合适

https://help.supermemo.org/wiki/Keyboard_shortcuts

**Comment by L-M-Sherlock** [comment]
你要的中文版快捷键：https://www.yuque.com/supermemo/wiki/keyboard-shortcuts

我个人不是很想继续扩大内置教程内容，如果你想加入，可以提交 PR
