### ISSUE TITLE
下载包时，检测到病毒

### ISSUE THREAD

**Issue by FlyWolfFreedom** [L-M-Sherlock/sm18-lazy-package#6]
![image](https://user-images.githubusercontent.com/27543126/207043331-dfc29baa-e66b-48fa-a5fe-413b127bf591.png)

**Comment by L-M-Sherlock** [comment]
什么检测软件啊？不要告诉我是腾讯安全管家或者 360 卫士哈。

**Comment by FlyWolfFreedom** [comment]
win10自带杀毒程序

Jarrett Ye ***@***.***> 于2022年12月22日周四 17:25写道：

**Comment by L-M-Sherlock** [comment]
我在 mac 上打包的，没有病毒。或许只是 SuperMemo 本身太老了，还在用 Delphi，容易被识别成病毒。
